# Generated by Django 5.2.8 on 2026-03-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('hospital_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Trust', 'Trust'), ('Clinic', 'Clinic')], max_length=20)),
                ('specialities', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('working_hours', models.TextField()),
                ('holidays', models.TextField(blank=True)),
                ('general_beds', models.IntegerField(default=0)),
                ('icu_beds', models.IntegerField(default=0)),
                ('emergency_beds', models.IntegerField(default=0)),
                ('insurance', models.TextField()),
                ('emergency_services', models.BooleanField(default=False)),
                ('is_24x7', models.BooleanField(default=False)),
                ('accreditation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hospital_images/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hospital_admin.hospital')),
            ],
        ),
    ]
